app = "vidforge"
primary_region = "lhr"

[env]
  FLY_VOLUME_PATH = "/data"
  NEXT_PUBLIC_BASE_URL = "https://vidforge.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "vidforge_data"
  destination = "/data"
